---
- name: mongodb | fetch GPG key
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  tags: mongodb

- name: mongodb | add 10 gen repository
  shell: echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  tags: mongodb

- name: mongodb | update apt
  apt: update_cache=yes
  tags: mongodb

- name: mongodb | install
  apt: package=mongodb-org state=latest
  tags: mongodb

- name: mongodb | add firewall exceptions
  shell: ufw allow 27017
  tags: mongodb

- name: mongodb | start
  service: name=mongod enabled=yes state=started
  tags: mongodb
